name: CI

on: [push, pull_request]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn lint
