name: CI

on: [push, pull_request]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn lint
